### ISSUE TITLE
IDEA 2022.2发布正式版了，能否支持一下

### ISSUE THREAD

**Issue by lijinshanmx** [bytedance/flutter_asset_literal_idea_plugin#10]
现在高版本上，搜索不到当前插件了，看提交应该是支持到213版本，现在已经有222了，希望能够调整一下配置，支持一下新版本～😄😄

**Comment by kaho954** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lijinshanmx** [comment]
最新版本的IDEA是：222.3739.54

**Comment by talisk** [comment]
Please use 1.7.7 and later.
