### ISSUE TITLE
Wrong path separator

### ISSUE THREAD

**Issue by Mabsten** [bytedance/flutter_asset_literal_idea_plugin#6]
Current platform and version:
Windows 10
IntelliJ ultimate 2020.3.3

Issue:
As path separator, the plugin mix windows (`\`) and standard (`/`) separator.

Example:
```
  assets:
    - assets\
    - assets/fonts\
```

Furthermore, it should be indicated in the readme that pubspec must already present the entry `assets`, otherwise it doesn't work.

**Comment by cikelengfeng** [comment]
@Mabsten Sorry for being late, I will deal with this issue in the near future.

**Comment by cikelengfeng** [comment]
@Mabsten The 1.7.4 version has been submitted to the plug-in store, and it will be updated in about two business days. Thank you very much for the bug you submitted. I hope this plug-in can help you.
