### ISSUE TITLE
在pubspec.yaml文件注入assets的路径后文件格式错误

### ISSUE THREAD

**Issue by wangzhanxian** [bytedance/flutter_asset_literal_idea_plugin#7]
使用的是window系统，本来是CRFL UTF-8格式，注入后变成LF UTF-8格式

**Comment by kaho954** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wangzhanxian** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

重新构建工程后又好了，打扰了
